name: .NET Core CI

on:
  push:
    branches:
      - main
      - github-actions-integration
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Clean NuGet cache
        run: dotnet nuget locals all --clear

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test ./Api.Tests/Api.Tests.csproj --no-build --verbosity detailed
